#!/usr/bin/env python3
"""
UNS Theme Generator
Genera tokens de diseño corporativos (Azul/Rojo UNS).
"""

from pathlib import Path


def generate_css(output_path: Path):
    theme_content = """/*
 * UNS CORPORATE THEME - Generated by Antigravity
 */

:root {
    /* Brand Colors */
    --uns-blue: #0052CC;
    --uns-red: #DC143C;

    /* HSL Tokens for transparency support */
    --uns-blue-hsl: 218, 100%, 40%;
    --uns-red-hsl: 348, 83%, 47%;

    /* UI colors (Light Mode) */
    --background: 0 0% 100%;
    --foreground: 222 47% 11%;
    --card: 0 0% 100%;
    --primary: 218 100% 40%;
    --primary-foreground: 210 40% 98%;
    --accent: 348 83% 47%;
    --accent-foreground: 210 40% 98%;
    --border: 214 32% 91%;
    --input: 214 32% 91%;
    --radius: 0.5rem;
}

.dark {
    /* UI colors (Dark Mode) */
    --background: 222 47% 11%;
    --foreground: 210 40% 98%;
    --card: 222 47% 11%;
    --primary: 218 100% 50%;
    --primary-foreground: 222 47% 11%;
    --accent: 348 83% 55%;
    --accent-foreground: 210 40% 98%;
    --border: 217 33% 18%;
    --input: 217 33% 18%;
}

body {
    font-family: 'Inter', 'Noto Sans JP', sans-serif;
    background-color: hsl(var(--background));
    color: hsl(var(--foreground));
}

.uns-card {
    background-color: hsl(var(--card));
    border: 1px solid hsl(var(--border));
    border-radius: var(--radius);
    padding: 1.5rem;
    box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
    backdrop-filter: blur(8px);
}
"""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(theme_content)
    print(f"✅ Tema generado exitosamente en: {output_path}")


if __name__ == "__main__":
    target = Path("uns-corporate-theme.css")
    generate_css(target)
