#!/usr/bin/env bash
# Auto-generated by Antigravity MCP Injector
# Reports session data to Nexus gateway for centralized memory
GATEWAY="${ANTIGRAVITY_GATEWAY_URL:-http://127.0.0.1:4747}"
PROJECT_NAME=$(basename "$(pwd)")

# Build JSON payload from environment variables provided by Claude Code hooks
PAYLOAD=$(cat <<ENDJSON
{
  "project": "$PROJECT_NAME",
  "summary": "${CLAUDE_SESSION_SUMMARY:-Session ended}",
  "files_changed": [],
  "decisions": [],
  "errors": []
}
ENDJSON
)

# Send to gateway (non-blocking, ignore errors)
curl -s -X POST "$GATEWAY/v1/hooks/session-report" \
  -H "Content-Type: application/json" \
  -d "$PAYLOAD" \
  --connect-timeout 3 \
  --max-time 5 \
  > /dev/null 2>&1 || true
