#!/usr/bin/env bash
# Auto-generated by Antigravity MCP Injector
# Uses the authenticated portable client; session.key is encrypted at rest.
GATEWAY="${ANTIGRAVITY_GATEWAY_URL:-http://127.0.0.1:4747}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
PORTABLE="$PROJECT_ROOT/.antigravity/runtime/current/antigravity-mcp/antigravity-mcp"
if [ ! -e "$PORTABLE" ] && [ ! -e "${PORTABLE}.exe" ]; then PORTABLE="$PROJECT_ROOT/.antigravity/runtime/current/antigravity-mcp"; fi
if [ -x "${PORTABLE}.exe" ]; then
  "${PORTABLE}.exe" session-report --gateway "$GATEWAY" || true
elif [ -x "$PORTABLE" ]; then
  "$PORTABLE" session-report --gateway "$GATEWAY" || true
else
  PRIVATE_PYTHON="$PROJECT_ROOT/.antigravity/runtime/current/python/python.exe"
  if [ ! -x "$PRIVATE_PYTHON" ]; then PRIVATE_PYTHON="$PROJECT_ROOT/.antigravity/runtime/current/python/bin/python3"; fi
  if [ ! -x "$PRIVATE_PYTHON" ]; then PRIVATE_PYTHON="$PROJECT_ROOT/.venv/Scripts/python.exe"; fi
  if [ ! -x "$PRIVATE_PYTHON" ]; then PRIVATE_PYTHON="$PROJECT_ROOT/.venv/bin/python3"; fi
  if [ -x "$PRIVATE_PYTHON" ]; then
    PYTHONPATH="$PROJECT_ROOT/.agent" "$PRIVATE_PYTHON" -m core.gateway_client session-report --gateway "$GATEWAY" || true
  fi
fi
