#!/usr/bin/env python3
"""
Playwright Testing Skill - E2E Test Automation

Capabilities:
- Generate E2E tests from user flows
- Execute tests across multiple browsers
- Analyze test results and failures
- Generate Page Object Models
"""

import asyncio
import json
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
import logging

logging.basicConfig(level=logging.INFO, format="[%(asctime)s] [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)


@dataclass
class TestStep:
    """A single step in a test flow."""

    action: str  # navigate, click, fill, assert, wait
    selector: str | None = None
    value: str | None = None
    url: str | None = None
    assertion: str | None = None


@dataclass
class TestFlow:
    """A complete test flow."""

    name: str
    description: str
    steps: list[TestStep] = field(default_factory=list)


@dataclass
class PageObject:
    """Page Object Model representation."""

    name: str
    url_pattern: str
    selectors: dict = field(default_factory=dict)
    actions: list[str] = field(default_factory=list)


class PlaywrightTestGenerator:
    """
    Generates Playwright tests from user flow descriptions.
    """

    def __init__(self, output_dir: str = "tests/e2e"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_test_file(self, flow: TestFlow) -> str:
        """Generate a complete pytest-playwright test file."""
        class_name = self._to_class_name(flow.name)
        method_name = self._to_method_name(flow.name)

        lines = [
            '"""',
            f"E2E Test: {flow.description}",
            "Auto-generated by Playwright Testing Skill",
            '"""',
            "",
            "import pytest",
            "from playwright.sync_api import Page, expect",
            "",
            "",
            f"class Test{class_name}:",
            f'    """Tests for {flow.name} flow."""',
            "",
            f"    def test_{method_name}(self, page: Page):",
            f'        """{flow.description}"""',
        ]

        for i, step in enumerate(flow.steps):
            lines.extend(self._generate_step_code(step, i))

        return "\n".join(lines)

    def _generate_step_code(self, step: TestStep, index: int) -> list[str]:
        """Generate code for a single test step."""
        lines = []

        if step.action == "navigate":
            lines.append(f"        # Step {index + 1}: Navigate")
            lines.append(f'        page.goto("{step.url}")')
            lines.append("")

        elif step.action == "click":
            lines.append(f"        # Step {index + 1}: Click")
            selector = self._generate_selector(step.selector)
            lines.append(f"        {selector}.click()")
            lines.append("")

        elif step.action == "fill":
            lines.append(f"        # Step {index + 1}: Fill")
            selector = self._generate_selector(step.selector)
            lines.append(f'        {selector}.fill("{step.value}")')
            lines.append("")

        elif step.action == "assert":
            lines.append(f"        # Step {index + 1}: Assert")
            lines.append(f"        {self._generate_assertion(step)}")
            lines.append("")

        elif step.action == "wait":
            lines.append(f"        # Step {index + 1}: Wait")
            if step.selector:
                selector = self._generate_selector(step.selector)
                lines.append(f'        {selector}.wait_for(state="visible")')
            else:
                lines.append(f"        page.wait_for_timeout({step.value or 1000})")
            lines.append("")

        elif step.action == "screenshot":
            lines.append(f"        # Step {index + 1}: Screenshot")
            lines.append(
                f'        page.screenshot(path="screenshots/{step.value or "step_" + str(index)}.png")'
            )
            lines.append("")

        return lines

    def _generate_selector(self, selector: str) -> str:
        """Generate robust Playwright selector."""
        if selector.startswith("[data-testid="):
            test_id = selector.split("=")[1].strip(']"')
            return f'page.get_by_test_id("{test_id}")'
        elif selector.startswith("#") or selector.startswith("."):
            return f'page.locator("{selector}")'
        elif selector.startswith("text="):
            text = selector.replace("text=", "")
            return f'page.get_by_text("{text}")'
        elif selector.startswith("role="):
            parts = selector.replace("role=", "").split(",")
            role = parts[0]
            name = parts[1] if len(parts) > 1 else None
            if name:
                return f'page.get_by_role("{role}", name="{name}")'
            return f'page.get_by_role("{role}")'
        elif selector.startswith("label="):
            label = selector.replace("label=", "")
            return f'page.get_by_label("{label}")'
        else:
            return f'page.locator("{selector}")'

    def _generate_assertion(self, step: TestStep) -> str:
        """Generate assertion code."""
        if step.assertion == "visible":
            selector = self._generate_selector(step.selector)
            return f"expect({selector}).to_be_visible()"
        elif step.assertion == "hidden":
            selector = self._generate_selector(step.selector)
            return f"expect({selector}).to_be_hidden()"
        elif step.assertion == "url":
            return f'expect(page).to_have_url("{step.value}")'
        elif step.assertion == "title":
            return f'expect(page).to_have_title("{step.value}")'
        elif step.assertion == "text":
            selector = self._generate_selector(step.selector)
            return f'expect({selector}).to_have_text("{step.value}")'
        else:
            return f"# Implementar: assertion para {step.assertion}"

    def _to_class_name(self, name: str) -> str:
        """Convert name to PascalCase class name."""
        return "".join(word.capitalize() for word in name.replace("-", "_").split("_"))

    def _to_method_name(self, name: str) -> str:
        """Convert name to snake_case method name."""
        return name.lower().replace("-", "_").replace(" ", "_")

    def generate_page_object(self, page: PageObject) -> str:
        """Generate Page Object Model class."""
        class_name = self._to_class_name(page.name) + "Page"

        lines = [
            '"""',
            f"Page Object: {page.name}",
            "Auto-generated by Playwright Testing Skill",
            '"""',
            "",
            "from playwright.sync_api import Page, expect",
            "",
            "",
            f"class {class_name}:",
            f'    """Page Object for {page.name}."""',
            "",
            "    def __init__(self, page: Page):",
            "        self.page = page",
            f'        self.url_pattern = "{page.url_pattern}"',
            "",
            "    # Selectors",
        ]

        for name, selector in page.selectors.items():
            lines.append("    @property")
            lines.append(f"    def {name}(self):")
            lines.append(f"        return {self._generate_selector(selector)}")
            lines.append("")

        lines.append("    # Actions")
        for action in page.actions:
            lines.append(f"    def {action}(self):")
            lines.append(f'        """Perform {action} action."""')
            lines.append(f"        # Implementar: acción {action}")
            lines.append("        pass")
            lines.append("")

        return "\n".join(lines)


class PlaywrightTestRunner:
    """
    Runs Playwright tests and collects results.
    """

    def __init__(self, test_dir: str = "tests/e2e"):
        self.test_dir = Path(test_dir)

    async def run(
        self, browsers: list[str] = None, parallel: int = 1, headed: bool = False
    ) -> dict:
        """Run Playwright tests."""
        if browsers is None:
            browsers = ["chromium"]
        logger.info(f"Running tests in {self.test_dir}")

        cmd = [
            sys.executable,
            "-m",
            "pytest",
            str(self.test_dir),
            "-v",
            f"--numprocesses={parallel}",
            "--html=playwright-report/report.html",
            "--self-contained-html",
        ]

        for browser in browsers:
            cmd.extend(["--browser", browser])

        if headed:
            cmd.append("--headed")

        logger.info(f"Executing: {' '.join(cmd)}")

        result = subprocess.run(cmd, capture_output=True, text=True)

        return {
            "exit_code": result.returncode,
            "stdout": result.stdout,
            "stderr": result.stderr,
            "passed": result.returncode == 0,
        }


class PlaywrightAnalyzer:
    """
    Analyzes Playwright test results and generates reports.
    """

    def analyze_report(self, report_dir: str) -> dict:
        """Analyze test report and extract insights."""
        report_path = Path(report_dir)

        analysis = {
            "total_tests": 0,
            "passed": 0,
            "failed": 0,
            "skipped": 0,
            "duration_ms": 0,
            "failures": [],
            "slow_tests": [],
        }

        # Check for JSON report
        json_report = report_path / "results.json"
        if json_report.exists():
            with open(json_report) as f:
                data = json.load(f)
                # Parse pytest JSON report format
                analysis["total_tests"] = data.get("summary", {}).get("total", 0)
                analysis["passed"] = data.get("summary", {}).get("passed", 0)
                analysis["failed"] = data.get("summary", {}).get("failed", 0)
                analysis["skipped"] = data.get("summary", {}).get("skipped", 0)

        return analysis


def parse_flow_from_string(flow_str: str, base_url: str) -> TestFlow:
    """Parse a simple flow string into TestFlow."""
    steps = []
    flow_parts = flow_str.split(",")

    for part in flow_parts:
        part = part.strip().lower()

        if part == "login":
            steps.extend(
                [
                    TestStep(action="navigate", url=f"{base_url}/login"),
                    TestStep(action="fill", selector="label=Email", value="test@example.com"),
                    TestStep(action="fill", selector="label=Password", value="password123"),
                    TestStep(action="click", selector="role=button,Login"),
                    TestStep(action="assert", assertion="url", value=f"{base_url}/dashboard"),
                ]
            )
        elif part == "dashboard":
            steps.extend(
                [
                    TestStep(action="navigate", url=f"{base_url}/dashboard"),
                    TestStep(action="assert", selector="text=Welcome", assertion="visible"),
                ]
            )
        elif part == "logout":
            steps.extend(
                [
                    TestStep(action="click", selector="role=button,Logout"),
                    TestStep(action="assert", assertion="url", value=f"{base_url}/login"),
                ]
            )
        else:
            # Generic page navigation
            steps.append(TestStep(action="navigate", url=f"{base_url}/{part}"))

    return TestFlow(
        name=flow_str.replace(",", "_"), description=f"Test flow: {flow_str}", steps=steps
    )


async def main():
    """Main entry point."""
    import argparse

    parser = argparse.ArgumentParser(description="Playwright Testing Skill")
    subparsers = parser.add_subparsers(dest="command", required=True)

    # Generate command
    gen_parser = subparsers.add_parser("generate", help="Generate tests")
    gen_parser.add_argument("--url", required=True, help="Base URL")
    gen_parser.add_argument("--flow", required=True, help="Flow steps (comma-separated)")
    gen_parser.add_argument("--output", "-o", default="tests/e2e", help="Output directory")

    # Run command
    run_parser = subparsers.add_parser("run", help="Run tests")
    run_parser.add_argument("--browser", nargs="+", default=["chromium"], help="Browsers")
    run_parser.add_argument("--parallel", type=int, default=1, help="Parallel workers")
    run_parser.add_argument("--headed", action="store_true", help="Run headed")

    # Analyze command
    analyze_parser = subparsers.add_parser("analyze", help="Analyze results")
    analyze_parser.add_argument(
        "--report-dir", default="playwright-report", help="Report directory"
    )

    args = parser.parse_args()

    if args.command == "generate":
        generator = PlaywrightTestGenerator(args.output)
        flow = parse_flow_from_string(args.flow, args.url)
        test_code = generator.generate_test_file(flow)

        output_file = Path(args.output) / f"test_{flow.name}.py"
        output_file.parent.mkdir(parents=True, exist_ok=True)
        output_file.write_text(test_code)

        print(f"✅ Generated test: {output_file}")
        print(f"\nGenerated code:\n{test_code}")

    elif args.command == "run":
        runner = PlaywrightTestRunner()
        result = await runner.run(browsers=args.browser, parallel=args.parallel, headed=args.headed)

        if result["passed"]:
            print("✅ All tests passed!")
        else:
            print("❌ Some tests failed")
            print(result["stderr"])

    elif args.command == "analyze":
        analyzer = PlaywrightAnalyzer()
        analysis = analyzer.analyze_report(args.report_dir)
        print(json.dumps(analysis, indent=2))


if __name__ == "__main__":
    asyncio.run(main())
